language: node_js
node_js:
  - '12'

services:
  - docker

before_install:
  - npm i @microservices/cli

script:
  - npx oms build
  - |
    output="$(npx oms run --silent encode -a content=foo)"
    if [ "$output" != 'Zm9v' ] ; then echo "$output"; exit 1; fi
